name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Run
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@6db134d15f3909ccc9eefd369f02bd1e9cffdf97 # v6.2.0
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Upload installation scripts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: gh release upload ${{ steps.release-drafter.outputs.tag_name }} installation/setup-mlir.sh installation/setup-mlir.ps1 --clobber
        env:
          GITHUB_TOKEN: ${{ github.token }}
