name: Update known versions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
      - name: Update known versions
        id: update-known-versions
        run: node dist/update-known-versions/index.js
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - id: create-token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create pull request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          token: ${{ steps.create-token.outputs.token }}
          commit-message: 👷 Update known versions
          title: 👷 Update known versions for ${{ steps.update-known-versions.outputs.latest-tag }}
          body: This PR updates the known versions to include `${{ steps.update-known-versions.outputs.latest-tag }}`.
          base: main
          labels: "documentation"
          branch: update-known-versions
          delete-branch: true
          sign-commits: true
