name: Update known versions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
      - name: Update known versions
        id: update-known-versions
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: node dist/update-known-versions/index.js
      - id: create-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write # Needed to push the update branch
          permission-pull-requests: write # Needed to open the update pull request
      - name: Create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ steps.create-token.outputs.token }}
          commit-message: 👷 Update known versions
          title: 👷 Update known versions for ${{ steps.update-known-versions.outputs.latest-tag }}
          body: This PR updates the known versions to include `${{ steps.update-known-versions.outputs.latest-tag }}`.
          base: main
          labels: "documentation"
          branch: update-known-versions
          delete-branch: true
          sign-commits: true
